# Generated by Django 6.0.7 on 2026-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
