# Generated by Django 6.0.7 on 2026-07-28 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_alter_room_tenant_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterUniqueTogether(
            name='monthlybill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommeterreading',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='month',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='total_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='room_reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent_app.roommeterreading'),
        ),
        migrations.AlterField(
            model_name='roommeterreading',
            name='units_consumed',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
