# Generated by Django 6.0.7 on 2026-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0004_room_address_room_advance_payment_room_move_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommeterreading',
            name='tenant_mobile_snapshot',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='roommeterreading',
            name='tenant_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
