# Generated by Django 6.0.7 on 2026-07-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_roommeterreading_tenant_mobile_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('tenant_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('tenant_email', models.CharField(blank=True, max_length=100, null=True)),
                ('room_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('aadhar_data', models.JSONField(blank=True, default=dict)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bills', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_histories', to='rent_app.room')),
            ],
            options={
                'verbose_name': 'Tenant History',
                'verbose_name_plural': 'Tenant Histories',
                'ordering': ['-move_in_date'],
            },
        ),
    ]
