# Generated by Django 6.0.7 on 2026-07-30 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0006_tenanthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybill',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
