# Generated by Django 6.0.7 on 2026-07-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0007_alter_monthlybill_month_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
