# Generated by Django 6.0.7 on 2026-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0010_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='aadhar_back',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='aadhar_front',
            field=models.TextField(blank=True, null=True),
        ),
    ]
